# View examples and documentation at https://deliverybot.dev/docs/
production:
  environment: production
  required_contexts: ["ci"]
  production_environment: true

staging:
  # Auto deploy on master.
  # auto_deploy_on: refs/heads/master
  # Wait for our ci pipeline to pass.
  required_contexts: ["ci"]
  environment: staging

test:
  # Set the transient environment flag to let GitHub and Deliverybot know that
  # this environment should be destroyed when the PR is closed.
  transient_environment: true
  production_environment: false

  # Dynamic environment name. The environment will look like pr123.
  #environment: pr${{ pr }}
  environment: test
