---

# - name: user | motd | remove motd"
#   command: update-rc.d motd remove

- name: user | motd | check if hushlogin exists
  stat:
    path: "/home/{{ ansible_user }}/.hushlogin"
  register: hushlogin

- name: user | motd | silence the login prompt
  file:
    dest: "/home/{{ ansible_user }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user }}"
    mode: "0775"
  when: not hushlogin.stat.exists
