#
# Below vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#group-variables
#

# Define the host as a control plane node
k3s_control_node: false
k3s_agent:
  with-node-id: true
  node-label:
    - "is-worker=true"
  flannel-backend: "none"  # This needs to be in quotes
  data-dir: "/data/rancher/k3s" # Move the states and object storage to a second disk '/data'
  kubelet-arg: 
    - feature-gates: "ExternalPolicyForExternalIP=true"
