---

- name: "cluster-calico: deploy operator"
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  command: "kubectl create -f {{ calico.operator_manifest }}"
  when:
  - "'master' in group_names"

- name: "cluster-calico: configure settings"
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  shell: |
    cat << EOF | kubectl create -f -
      apiVersion: operator.tigera.io/v1
      kind: Installation
      metadata:
        name: default
      spec:
        calicoNetwork:
          ipPools:
          - blockSize: 26
            cidr: 10.43.0.0/16
            encapsulation: VXLANCrossSubnet
            natOutgoing: Enabled
            nodeSelector: all()
  when:
  - "'master' in group_names"

- name: "cluster-calico: configure BGP-peer"
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  shell: |
    cat << EOF | kubectl create -f -
      apiVersion: crd.projectcalico.org/v1
      kind: BGPPeer
      metadata:
        name: global
      spec:
        peerIP: {{ calico.bgp.peer }}
        asNumber: {{ calico.bgp.as }}
  when: "'master' in group_names and calico.bgp.enabled is defined and calico.bgp.enabled == true"

- name: "cluster-calico: configure BGP-externalIPs"
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  shell: |
    cat << EOF | kubectl create -f -
      apiVersion: crd.projectcalico.org/v1
      kind: BGPConfiguration
      metadata:
        name: default
      spec:
        serviceExternalIPs:
        - cidr: {{ calico.bgp.externalIPs }}
  when: "'master' in group_names and calico.bgp.enabled is defined and calico.bgp.enabled == true"
