apiVersion: stash.appscode.com/v1beta1
kind: BackupBlueprint
metadata:
  name: default-workload-blueprint
spec:
  # ============== Blueprint for Repository ==========================
  backend:
    s3:
      endpoint: minio # use server URL for s3 compatible other storage service
      bucket: k8s-backups
      prefix: /stash-backup/${TARGET_NAMESPACE}/${TARGET_KIND}/${TARGET_NAME}
    storageSecretName: restic-backup-credentials
  # ============== Blueprint for BackupConfiguration =================
  schedule: "0 */4 * * *"
  retentionPolicy:
    name: 'keep-last-30'
    keepLast: 30
    prune: true
