# all:
#   vars:
#     ansible_user: ubuntu

master:
  hosts:
    k3s-master-a:
  vars:
    type: master

nodes:
  hosts:
    r610-0:
    r610-1:
    r610-2:
  vars:
    type: worker

ceph:
  hosts:
    r610-0:
    r610-1:
    r610-2:
  vars:
    storage: ceph

nfs:
  hosts:
  vars:
    storage: nfs

k3s_cluster:
  children:
    master:
    nodes:

storage:
  children:
    ceph:
    nfs:

vault:
  hosts:
    localhost:
      ansible_connection: local
