apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: kube-system
spec:
  ports:
    - name: nfs
      port: 2049
  selector:
    role: nfs-server
  type: LoadBalancer
  loadBalancerIP: 10.20.50.100
