---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
spec:
  releaseName: helm-operator
  chart:
    repository: https://charts.fluxcd.io/
    name: helm-operator
    version: 0.6.0
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/carpenike/k3s-bootstrap/master/cluster/flux/helm-operator/flux-helm-operator-values.yaml
