---

- name: "cluster-crds: create"
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  command: "kubectl create -f {{ item }}"
  with_items:
  - "{{ crds }}"
  when:
  - "'master' in group_names"