---

- name: "kernel: enable modules"
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - br_netfilter
  - overlay
  - rbd

- name: "kernel: enable modules on boot"
  copy:
    content: "{{ item }}"
    dest: "/etc/modules-load.d/{{ item }}.conf"
  with_items:
  - br_netfilter
  - overlay
  - rbd

# Blacklist for PiAware: https://hub.docker.com/r/mikenye/piaware
- name: "kernel: blacklist modules"
  community.general.kernel_blacklist:
    name: "{{ item }}"
    state: present
  with_items:
  - dvb_usb_rtl28xxu
  - rtl2832
  - rtl2832_sdr

# Blacklist for PiAware: https://hub.docker.com/r/mikenye/piaware
- name: "kernel: blacklist modules on boot"
  copy:
    content: "blacklist {{ item }}"
    dest: "/etc/modprobe.d/{{ item }}.conf"
  with_items:
  - dvb_usb_rtl28xxu
  - rtl2832
  - rtl2832_sdr
