---

# Set /proc/sys/net/bridge/bridge-nf-call-iptables to 1 by running
# sysctl net.bridge.bridge-nf-call-iptables=1 to pass bridged IPv4 traffic to iptables’ chains.
# This is a requirement for some CNI plugins to work.
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- name: "kernel: enable modules"
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - br_netfilter
  - overlay

- name: "kernel: enable modules on boot"
  copy:
    content: "{{ item }}"
    dest: "/etc/modules-load.d/{{ item }}.conf"
  with_items:
  - br_netfilter
  - overlay

# Blacklist for PiAware: https://hub.docker.com/r/mikenye/piaware
- name: "kernel: blacklist modules"
  kernel_blacklist:
    name: "{{ item }}"
    state: present
  with_items:
  - dvb_usb_rtl28xxu
  - rtl2832
  - rtl2832_sdr

- name: "kernel: blacklist modules on boot"
  copy:
    content: "blacklist {{ item }}"
    dest: "/etc/modprobe.d/{{ item }}.conf"
  with_items:
  - dvb_usb_rtl28xxu
  - rtl2832
  - rtl2832_sdr
