---

- name: "package-prune: remove snap packages"
  become: true
  ignore_errors: true
  command: snap remove {{ item }}
  with_items:
  - lxd
  - core18
  - snapd
  when: ansible_distribution == 'Ubuntu'

- name: "package-prune: remove packages"
  become: true
  apt:
    name:
    - apport
    - bcache-tools
    - btrfs-progs
    - byobu
    - cloud-init
    - cloud-guest-utils
    - cloud-initramfs-copymods
    - cloud-initramfs-dyn-netconf
    - friendly-recovery
    - fwupd
    - landscape-common
    - lxd-agent-loader
    - ntfs-3g
    - open-vm-tools
    - plymouth
    - plymouth-theme-ubuntu-text
    - popularity-contest
    - snapd
    - sosreport
    - tmux
    - ubuntu-advantage-tools
    - ufw
    state: absent
    autoremove: true

- name: "package-prune: forbid packages to be installed"
  become: true
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - apport
    - bcache-tools
    - btrfs-progs
    - byobu
    - cloud-init
    - cloud-guest-utils
    - cloud-initramfs-copymods
    - cloud-initramfs-dyn-netconf
    - friendly-recovery
    - fwupd
    - landscape-common
    - lxd-agent-loader
    - ntfs-3g
    - open-vm-tools
    - plymouth
    - plymouth-theme-ubuntu-text
    - popularity-contest
    - snapd
    - sosreport
    - tmux
    - ubuntu-advantage-tools
    - ufw

- name: "package-prune: remove file and directory cruft"
  become: true
  file:
    state: absent
    path: "{{ item }}"
  with_items:
  - "/home/{{ ansible_user }}/.snap"
  - "/snap"
  - "/var/snap"
  - "/var/lib/snapd"
  - "/var/cache/snapd"
  - "/usr/lib/snapd"
  - "/etc/cloud"
  - "/var/lib/cloud"
