---

- name: "package-prune: remove snap packages"
  become: true
  ignore_errors: true
  command: snap remove {{ item }}
  with_items:
  - lxd
  - core18
  - snapd
  when: ansible_distribution == 'Ubuntu'

- name: "package-prune: remove packages"
  become: true
  apt:
    name:
    - apport
    - popularity-contest
    - snapd
    - sosreport
    - ubuntu-advantage-tools
    - cloud-init
    state: absent
    autoremove: true

- name: "package-prune: forbid packages to be installed"
  become: true
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
  - apport
  - popularity-contest
  - snapd
  - sosreport
  - ubuntu-advantage-tools
  - cloud-init

- name: "package-prune: remove file and directory cruft"
  become: true
  file:
    state: absent
    path: "{{ item }}"
  with_items:
  - "/home/{{ ansible_user }}/.snap"
  - "/snap"
  - "/var/snap"
  - "/var/lib/snapd"
  - "/var/cache/snapd"
  - "/usr/lib/snapd"
  - "/etc/cloud"
  - "/var/lib/cloud"
