---
- name: "filesystem: disable swap"
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: "filesystem: disable swap in /etc/fstab"
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none

- name: "filesystem: mount bpffs"
  ansible.posix.mount:
    src: bpffs
    path: /sys/fs/bpf
    fstype: bpf
    state: mounted
    opts: rw,nosuid,nodev,noexec,relatime,mode=700