---
- name: filesystem | swap | disable
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: filesystem | swap | disable in /etc/fstab
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none
