---
- name: "filesystem: disable"
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: "filesystem: disable in /etc/fstab"
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none
