---

#
# https://github.com/longhorn/longhorn/issues/1210#issuecomment-671689746
#

- name: multipath | create multipath config directory
  become: true
  file:
    path: "/etc/multipath/conf.d"
    state: directory

- name: multipath | blacklist multipath for sd*
  become: true
  copy:
    content: |
      blacklist {
        device {
          vendor "VMware"
          product "Virtual disk"
        }
      }
    dest: /etc/multipath/conf.d/ubuntu-20-on-vmware.conf

- name: multipath | restart systemd service
  systemd:
    name: multipathd.service
    daemon_reload: no
    enabled: yes
    state: restarted
