---
- name: kernel | increase loop device count
  become: true
  replace:
    path: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX_DEFAULT=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$'
    replace: '\1 {{ option }}={{ value }}\2'
  vars:
    option: max_loop
    value: 32

- name: kernel | enable modules
  become: true
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
  - br_netfilter
  - overlay
  - rbd
  - ip_vs

- name: kernel | enable modules on boot
  become: true
  copy:
    content: "{{ item }}"
    dest: "/etc/modules-load.d/{{ item }}.conf"
  loop:
  - br_netfilter
  - overlay
  - rbd
  - ip_vs
