---
- name: kernel | enable modules
  become: true
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
  - br_netfilter
  - overlay
  - rbd
  - ip_vs

- name: kernel | enable modules on boot
  become: true
  copy:
    content: "{{ item }}"
    dest: "/etc/modules-load.d/{{ item }}.conf"
  loop:
  - br_netfilter
  - overlay
  - rbd
  - ip_vs
