---

- include: host.yml
- include: time.yml
- include: packages.yml
- include: power-button.yml
- include: motd.yml
- include: kernel.yml
- include: network.yml
- include: filesystem.yml
- include: unattended-upgrades.yml
- include: user.yml
- include: keepalived.yml
  when:
  - k3s_control_node is defined
  - k3s_control_node 
  - keepalived.enabled is defined
  - keepalived.enabled
