---

- include: host.yml
  tags:
  - host

- include: time.yml
  tags:
  - time

- include: packages.yml
  tags:
  - packages

- include: power-button.yml
  tags:
  - power-button

- include: motd.yml
  tags:
  - motd

- include: kernel.yml
# - include: kernel-arm64.yml
  tags:
  - kernel

# - include: network.yml
- include: network-arm64.yml
  tags:
  - network

- include: filesystem.yml
  tags:
  - filesystem
  
- include: disable-multipath.yml
  tags:
  - disable-multipath

- include: unattended-upgrades.yml
  tags:
  - unattended-upgrades

- include: user.yml
  tags:
  - user

- include: keepalived.yml
  when:
  - k3s_control_node is defined
  - k3s_control_node 
  - keepalived.enabled is defined
  - keepalived.enabled
  tags:
  - keepalived

- include: rsyslog.yml
  when:
  - rsyslog.enabled is defined 
  - rsyslog.enabled
  tags:
  - rsyslog
