---

- name: user | add to sudoers
  become: true
  copy:
    content: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ ansible_user }}_nopasswd"
    mode: "0440"

- name: user | add additional SSH public keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  with_items:
  - "{{ ssh_authorized_keys }}"

- name: user | check if hushlogin exists
  stat:
    path: "/home/{{ ansible_user }}/.hushlogin"
  register: hushlogin

- name: user | silence the login prompt
  file:
    dest: "/home/{{ ansible_user }}/.hushlogin"
    state: touch
    owner: "{{ ansible_user }}"
    mode: "0775"
  when: not hushlogin.stat.exists

- name: user | create config directory
  file:
    path: "/home/{{ ansible_user }}/.config"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    mode: "0775"

- name: user | create neofetch directory
  file:
    path: "/home/{{ ansible_user }}/.config/neofetch"
    state: directory
    recurse: true
    owner: "{{ ansible_user }}"
    mode: "0775"

- name: user | copy neofetch configuration
  copy:
    owner: "{{ ansible_user }}"
    mode: "0775"
    content: |
      print_info() {
          prin
          info title
          info "OS" distro
          info "Kernel" kernel
          info "CPU Usage" cpu_usage
          info "Memory Usage" memory
          info "Disk" disk
          info "Local IP" local_ip
          info "Uptime" uptime
      }
    dest: "/home/{{ ansible_user }}/.config/neofetch/config.conf"

- name: user | enable neofetch on login
  copy:
    content: "neofetch --ascii_distro ubuntu_small"
    dest: "/home/{{ ansible_user }}/.bash_profile"
    owner: "{{ ansible_user }}"
    mode: "0775"