---

# IP address of node
ansible_host: "172.16.20.11"

# IP Address to advertise for this node
# for more k3s host variables, see
# https://github.com/PyratLabs/ansible-role-k3s#host-variables
k3s_node_ip_address: "{{ ansible_host }}"

# Format and mount a device for longhorn
longhorn:
  enabled: true
  disks:
  - "/dev/sdb"
  filesystem: "ext4"
  mountpoint: "/var/lib/longhorn"
  # Defines additional lvcreate options (e.g. stripes, stripesize, etc)
  # lvcreate_opts: ""
  # Defines additional mount options (e.g. noatime, noexec, etc)
  # mount_opts: ""

# Apply system-upgrade label, for use with
# https://rancher.com/docs/k3s/latest/en/upgrades/automated/
k3s_system_upgrade: true