---

- name: "network: install packages"
  apt:
    name:
    - dnsutils
    - ethtool
    - iperf3
    - iputils-ping
    - net-tools
    - nmap
    - traceroute
    install_recommends: false
    update_cache: true
    autoclean: true
    autoremove: true
  register: apt_install_network_packages
  retries: 5
  until: apt_install_network_packages is success

- name: "network: update bridged IPv4 traffic to iptables chains"
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf

- name: "network: update bridged IPv4 traffic to ip6tables chains"
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf

- name: "network: update bridged IPv4 traffic forwarding"
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
