---

- name: "cluster-cni: deploy tigera operator to k3s manifest directory"
  become: true
  get_url:
    url: "{{ calico.operator_manifest }}"
    dest: "{{ k3s_server_manifests_dir }}/tigera-operator.yaml"
    mode: 0644
  when:
  - "'master' in group_names and calico.enabled is defined and calico.enabled"

- name: "cluster-cni: deploy calico configuration to k3s manifest directory"
  become: true
  template:
    src: "{{ item }}"
    dest: "{{ k3s_server_manifests_dir }}/{{ item | basename | replace('.j2','') }}"
    mode: 0644
  with_items:
  - "calico-installation.yaml.j2"
  when:
  - "'master' in group_names and calico.enabled is defined and calico.enabled"

- name: "cluster-cni: deploy calico configure BGP-peer to k3s manifest directory"
  become: true
  template:
    src: "{{ item }}"
    dest: "{{ k3s_server_manifests_dir }}/{{ item | basename | replace('.j2','') }}"
    mode: 0644
  with_items:
  - "calico-bgpeer.yaml.j2"
  when:
  - "'master' in group_names and calico.bgp.enabled is defined and calico.bgp.enabled == true"

- name: "cluster-cni: deploy calico configure BGP-configuration to k3s manifest directory"
  become: true
  template:
    src: "{{ item }}"
    dest: "{{ k3s_server_manifests_dir }}/{{ item | basename | replace('.j2','') }}"
    mode: 0644
  with_items:
  - "calico-bgpconfiguration.yaml.j2"
  when:
  - "'master' in group_names and calico.bgp.enabled is defined and calico.bgp.enabled == true"