---

- name: cluster-cni | calico | deploy tigera operator to k3s manifest directory
  become: true
  get_url:
    url: "{{ calico.operator_manifest }}"
    dest: "{{ k3s_server_manifests_dir }}/tigera-operator.yaml"
    mode: 0644

# Enable eBPF - in tech preview, still a few kinks to work out...
# https://docs.projectcalico.org/maintenance/enabling-bpf
- name: cluster-cni | calico | deploy eBPF configuration to k3s manifest directory
  become: true
  template:
    src: "calico-ebpf-configmap.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/calico-ebpf-configmap.yaml"
    mode: 0644
  when: calico.ebpf.enabled is defined
        and calico.ebpf.enabled

- name: cluster-cni | calico | deploy configuration to k3s manifest directory
  become: true
  template:
    src: "calico-installation.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/calico-installation.yaml"
    mode: 0644

- name: cluster-cni | calico | deploy configure BGP-peer to k3s manifest directory
  become: true
  template:
    src: "calico-bgppeer.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/calico-bgppeer.yaml"
    mode: 0644
  when: calico.bgp.enabled is defined 
        and calico.bgp.enabled

- name: cluster-cni | calico | deploy configure BGP-configuration to k3s manifest directory
  become: true
  template:
    src: "calico-bgpconfiguration.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/calico-bgpconfiguration.yaml"
    mode: 0644
  when: calico.bgp.enabled is defined 
        and calico.bgp.enabled
