---

- name: cluster-cni | cilium | deploy secret for etcd to k3s manifest directory
  become: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  shell: >
    kubectl create secret generic -n kube-system cilium-etcd-secrets
    --from-file=etcd-client-ca.crt=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
    --from-file=etcd-client.key=/var/lib/rancher/k3s/server/tls/etcd/server-client.key
    --from-file=etcd-client.crt=/var/lib/rancher/k3s/server/tls/etcd/server-client.crt
    --dry-run=client
    --output=yaml
    > "{{ k3s_server_manifests_dir }}/cilium-etcd-secrets.yaml"
  when: cilium_kube_router.cilium.etcd is defined
        and cilium_kube_router.cilium.etcd

- name: cluster-cni | cilium | deploy configuration to k3s manifest directory
  become: true
  template:
    src: "cilium-helmchart.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/cilium-helmchart.yaml"
    mode: 0644

- name: cluster-cni | cilium | deploy kube-router to k3s manifest directory
  become: true
  template:
    src: "kube-router.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/kube-router.yaml"
    mode: 0644