---

- name: "cluster-cni: create cilium secret for etcd"
  become: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  shell: >
    kubectl create secret generic -n kube-system cilium-etcd-secrets
    --from-file=etcd-client-ca.crt=/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt
    --from-file=etcd-client.key=/var/lib/rancher/k3s/server/tls/etcd/server-client.key
    --from-file=etcd-client.crt=/var/lib/rancher/k3s/server/tls/etcd/server-client.crt
    --dry-run=client
    --output=yaml
    > "{{ k3s_server_manifests_dir }}/cilium-etcd-secrets.yaml"
  when:
  - "'master' in group_names and cilium_kube_router.enabled is defined and cilium_kube_router.enabled and cilium_kube_router.cilium.etcd is defined and cilium_kube_router.cilium.etcd"

- name: "cluster-cni: deploy cilium configuration to k3s manifest directory"
  become: true
  template:
    src: "{{ item }}"
    dest: "{{ k3s_server_manifests_dir }}/{{ item | basename | replace('.j2','') }}"
    mode: 0644
  with_items:
  - "cilium-helmchart.yaml.j2"
  when:
  - "'master' in group_names and cilium_kube_router.enabled is defined and cilium_kube_router.enabled"

- name: "cluster-cni: deploy kube-router"
  become: true
  template:
    src: "{{ item }}"
    dest: "{{ k3s_server_manifests_dir }}/{{ item | basename | replace('.j2','') }}"
    mode: 0644
  with_items:
  - "kube-router.yaml.j2"
  when:
  - "'master' in group_names and cilium_kube_router.enabled is defined and cilium_kube_router.enabled"