apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-provisioner-0
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/tank/share/k8s
  claimRef:
    namespace: kube-system
    name: data-nfs-server-provisioner-0
