---
# k3s options
k3s_release_version: false
k3s_no_traefik: true
k3s_no_servicelb: true
k3s_use_experimental: false
k3s_control_workers: true
k3s_cluster_cidr: "10.42.0.0/16"
k3s_service_cidr: "10.43.0.0/16"
k3s_use_docker: false
k3s_no_flannel: false
#k3s_flannel_backend: "host-gw"
k3s_copy_config_local: false
k3s_master_lb: "{{ hostvars[groups['master'][0]]['ansible_host'] }}"

# ansible options
ansible_user: "ubuntu"
local_user: "{{ ansible_user }}"

# k3s options
#k3s_master: "{{ hostvars[groups['master'][0]]['ansible_nodename'] }}" ## Only used in tear-down. Needs to be re-worked.

# github options
github_username:
github_k8s_reponame: k8s-cluster
github_k8s_reponame_branch: master

# ceph options
ceph:
  converged: true
  zap_disks: false
  disks:
    - /dev/sdb
    - /dev/sdc
    - /dev/sdd

# helm options
helm_operator: enabled

# server options
timezone: America/New_York
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
REPO_ROOT: "{{ lookup('pipe', 'git rev-parse --show-toplevel') }}"
kubernetes_pod_network:
  cni: flannel # calico / flannel
  bgp: disabled # Enabled / Disabled
  calico_manifest_file: "{{ REPO_ROOT }}/cluster/kube-system/calico/calico.yaml"
  calico_bgp_peer: 10.20.0.1
  calico_bgp_as: 64512
  cidr: '10.244.0.0/16'
allowed_kubernetes_access:
  - 10.9.18.225
  - 10.20.100.46
kubernetes_prometheus_alertmanager_manifest_file: https://raw.githubusercontent.com/helm/charts/master/stable/prometheus-operator/crds/crd-alertmanager.yaml
kubernetes_prometheus_podmonitor_manifest_file: https://raw.githubusercontent.com/helm/charts/master/stable/prometheus-operator/crds/crd-podmonitor.yaml
kubernetes_prometheus_prometheus_manifest_file: https://raw.githubusercontent.com/helm/charts/master/stable/prometheus-operator/crds/crd-prometheus.yaml
kubernetes_prometheus_prometheusrules_manifest_file: https://raw.githubusercontent.com/helm/charts/master/stable/prometheus-operator/crds/crd-prometheusrules.yaml
kubernetes_prometheus_servicemonitor_manifest_file: https://raw.githubusercontent.com/coreos/prometheus-operator/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
kubernetes_flux_values: "{{ REPO_ROOT }}/cluster/flux/flux/flux-values.yaml"
kubernetes_helm_operator_values: "{{ REPO_ROOT }}/cluster/flux/helm-operator/helm-operator-values.yaml"
