---

- name: cluster | calico | get all calicoctl releases
  get_url:
    url: https://api.github.com/repos/projectcalico/calicoctl/releases
    dest: /tmp/calicoctl.releases.json

- name: cluster | calico | get latest calicoctl release version
  shell: >
    cat /tmp/calicoctl.releases.json | jq --raw-output '.[0].tag_name'
  register: calicoctl_latest_release

- name: cluster | calico | download latest calicoctl
  become: yes
  get_url:
    url: "https://github.com/projectcalico/calicoctl/releases/download/{{ calicoctl_latest_release.stdout_lines[0] }}/calicoctl-linux-amd64"
    dest: "/usr/local/bin/calicoctl"
    mode: 0755

- name: cluster | calico | deploy tigera operator to k3s manifest directory
  become: true
  get_url:
    url: "{{ calico.operator_manifest }}"
    dest: "{{ k3s_server_manifests_dir }}/tigera-operator.yaml"
    mode: 0644

- name: cluster | calico | deploy configuration to k3s manifest directory
  become: true
  template:
    src: "calico-installation.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/calico-installation.yaml"
    mode: 0644

- name: cluster | calico | deploy configure BGP-peer to k3s manifest directory
  become: true
  template:
    src: "calico-bgppeer.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/calico-bgppeer.yaml"
    mode: 0644
  when: 
  - calico.bgp.enabled is defined 
  - calico.bgp.enabled

- name: cluster | calico | deploy configure BGP-configuration to k3s manifest directory
  become: true
  template:
    src: "calico-bgpconfiguration.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/calico-bgpconfiguration.yaml"
    mode: 0644
  when:
  - calico.bgp.enabled is defined 
  - calico.bgp.enabled

#
# Enable eBPF and DSR
# https://docs.projectcalico.org/maintenance/enabling-bpf
#

- name: cluster | calico | deploy eBPF configuration to k3s manifest directory
  become: true
  template:
    src: "calico-ebpf-configmap.yaml.j2"
    dest: "{{ k3s_server_manifests_dir }}/calico-ebpf-configmap.yaml"
    mode: 0644
  when:
  - calico.ebpf.enabled is defined
  - calico.ebpf.enabled

- name: cluster | calico | wait for resources to be deployed
  pause:
    seconds: "30"
  when:
  - calico.ebpf.enabled is defined
  - calico.ebpf.enabled

- name: cluster | calico | enable eBPF
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
    DATASTORE_TYPE: "kubernetes"
  shell: >
    calicoctl patch felixconfiguration default --patch='{"spec": {"bpfEnabled": true}}'
  when:
  - k3s_control_node is defined
  - k3s_control_node 
  - calico.ebpf.enabled is defined
  - calico.ebpf.enabled

- name: cluster | calico | enable DSR
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
    DATASTORE_TYPE: "kubernetes"
  shell: >
    calicoctl patch felixconfiguration default --patch='{"spec": {"bpfExternalServiceMode": "DSR"}}'
  when:
  - k3s_control_node is defined
  - k3s_control_node 
  - calico.ebpf.enabled is defined
  - calico.ebpf.enabled
