---

- name: time | restart systemd service
  service:
    name: systemd-timesyncd.service
    state: restarted
  listen: systemd-timesyncd configuration changed

- name: time | write adjtime
  command: hwclock --systohc
  listen: systemd-timesyncd configuration changed
  when: ansible_virtualization_role == "host" 
        or ansible_virtualization_role == "NA"