---

- name: "keepalived: configure"
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived
  when:
  - "'master' in group_names and keepalived.enabled is defined and keepalived.enabled == true"
