---

- name: keepalived | configure | copy configuration
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: restart keepalived
  when: k3s_control_node is defined
      and k3s_control_node
      and keepalived.enabled is defined 
      and keepalived.enabled
