---

k3s_runtime_config: "{{
  (k3s_control_node is defined and k3s_control_node)
  | ternary(
      (k3s_server | default({})) | combine (k3s_agent | default({})),
      (k3s_agent | default({})),
      (k3s_server | default({})) | combine (k3s_agent | default({})))
}}"

# Data directory location for k3s
k3s_data_dir: "{{ k3s_runtime_config['data-dir'] | default('/var/lib/rancher/k3s') }}"

# Prometheus Operator version from:
# https://github.com/prometheus-operator/prometheus-operator/releases
prometheus_operator_version: "0.42"

# URLs to the  Prometheus Operator CRDs
prometheus_operator_crds:
- "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-{{ prometheus_operator_version }}/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml"
- "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-{{ prometheus_operator_version }}/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml"
- "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-{{ prometheus_operator_version }}/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml"
- "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-{{ prometheus_operator_version }}/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml"
- "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-{{ prometheus_operator_version }}/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml"
- "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-{{ prometheus_operator_version }}/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml"
- "https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/release-{{ prometheus_operator_version }}/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml"
