apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-tank-share-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: nfs-tank-share-pvc
  storageClassName: nfs-client
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: nfs-server.kube-system.svc.cluster.local
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-tank-share-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Mi
