---

- name: packages | upgrade all packages
  apt:
    name: "*"
    state: latest
  register: apt_update
  retries: 5
  until: apt_update is success

- name: packages | install common
  become: true
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - gnupg-agent
    - gnupg2
    - haveged
    - hdparm
    # - htop # outdated v2, see below
    - jq
    - lvm2
    - neofetch
    - nfs-common
    - ntpdate
    - psmisc
    - python3
    - python3-pip
    - python3-openssl
    - rsync
    - software-properties-common
    - unzip
    - unattended-upgrades
    - vim
    # Network tools
    - arptables
    - dnsutils
    - ebtables
    - ethtool
    - iperf3
    - iputils-ping
    - ipvsadm
    - net-tools
    - netcat
    - nmap
    - socat
    - traceroute
    install_recommends: false
    update_cache: true
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success

# Until focal has https://launchpad.net/ubuntu/+source/htop
- name: packages | install latest htop
  become: true
  apt:
    deb: https://launchpad.net/ubuntu/+archive/primary/+files/htop_3.0.2-1_amd64.deb
  register: apt_install_htop
  retries: 5
  until: apt_install_htop is success

- name: packages | gather install packages
  package_facts:
    manager: auto

- name: packages | check if snap is installed
  debug:
    msg: 'snapd is installed'
  register: snapd_check
  when: '"snapd" in ansible_facts.packages'

- name: packages | remove snap packages
  become: true
  command: snap remove {{ item }}
  with_items:
  - lxd
  - core18
  - snapd
  when: ansible_distribution == 'Ubuntu' and snapd_check.failed is defined

- name: packages | remove packages
  become: true
  apt:
    name:
    - apparmor
    - apport
    - bcache-tools
    - btrfs-progs
    - byobu
    - cloud-init
    - cloud-guest-utils
    - cloud-initramfs-copymods
    - cloud-initramfs-dyn-netconf
    - friendly-recovery
    - fwupd
    - landscape-common
    - lxd-agent-loader
    - ntfs-3g
    - open-vm-tools
    - plymouth
    - plymouth-theme-ubuntu-text
    - popularity-contest
    - snapd
    - sosreport
    - tmux
    - ubuntu-advantage-tools
    - ufw
    state: absent
    autoremove: true

- name: packages | remove file and directory cruft
  become: true
  file:
    state: absent
    path: "{{ item }}"
  with_items:
  - "/home/{{ ansible_user }}/.snap"
  - "/snap"
  - "/var/snap"
  - "/var/lib/snapd"
  - "/var/cache/snapd"
  - "/usr/lib/snapd"
  - "/etc/cloud"
  - "/var/lib/cloud"
