---

- name: cluster | meta | apply master taints
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  command: kubectl taint --overwrite node {{ hostvars[item]['ansible_hostname'] }} node-role.kubernetes.io/master=true:NoSchedule
  with_items:
  - "{{ groups['master'] }}"
  register: apply_master_taints
  retries: 3
  when: k3s_control_node is defined
        and k3s_control_node
        and k3s_taint_master is defined
        and k3s_taint_master

- name: cluster | meta | apply worker annotations
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  command: kubectl label --overwrite node {{ hostvars[item]['ansible_hostname'] }} node-role.kubernetes.io/worker=true
  with_items:
  - "{{ groups['worker'] }}"
  register: apply_worker_annotations
  retries: 3
  until: apply_worker_annotations is success
  when: k3s_control_node is defined
        and k3s_control_node

- name: cluster | meta | apply system-upgrade annotations
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  command: kubectl label --overwrite node {{ hostvars[item]['ansible_hostname'] }} k3s-upgrade=true
  with_items:
  - "{{ groups['master'] }}"
  - "{{ groups['worker'] }}"
  register: apply_system_upgrade_annotations
  retries: 3
  until: apply_system_upgrade_annotations is success
  when: k3s_control_node is defined
        and k3s_control_node
        and hostvars[item].k3s_system_upgrade is defined 
        and hostvars[item].k3s_system_upgrade

- name: cluster | meta | remove system-upgrade annotations
  become: true
  run_once: true
  environment:
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  command: kubectl label --overwrite node {{ hostvars[item]['ansible_hostname'] }} k3s-upgrade-
  with_items:
  - "{{ groups['master'] }}"
  - "{{ groups['worker'] }}"
  register: remove_system_upgrade_annotations
  retries: 3
  until: remove_system_upgrade_annotations is success
  when: k3s_control_node is defined
        and k3s_control_node
        and (hostvars[item].k3s_system_upgrade is not defined 
          or not hostvars[item].k3s_system_upgrade)
