---

- name: cluster-registry | create /etc/rancher/k3s
  become: true
  file:
    path: "/etc/rancher/k3s"
    state: directory

- name: cluster-registry | configure mirrors and custom registries
  become: true
  template:
    src: "registries.yaml.j2"
    dest: "/etc/rancher/k3s/registries.yaml"
    mode: 0644
  notify: k3s registry configuration changed

- name: cluster-registry | start k3s systemd service
  systemd:
    name: k3s
    enabled: true
    state: started
