---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: minio
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:RELEASE.*
spec:
  releaseName: minio
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: minio
    version: 5.0.7
  values:
    image:
      repository: jessestuart/minio
      tag: RELEASE.2019-12-17T23-16-33Z
    persistence:
      storageClass: nfs
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
