---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: minio
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:RELEASE.*
spec:
  releaseName: minio
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: minio
    version: 5.0.7
  values:
    image:
      repository: jessestuart/minio
      tag: RELEASE.2019-12-17T23-16-33Z
    persistence:
      existingClaim: "nfs-tank-share-pvc"
      subPath: "minio"
    ingress:
      enabled: true
      hosts:
        - minio.k8s-at-home.com
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
