apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: consul
  namespace: kube-system
spec:
  releaseName: consul
  helmVersion: v3
  rollback:
    enabled: true
  chart:
    git: https://github.com/hashicorp/consul-helm
    ref: v0.16.2
    path: .
  values:
    server:
      enabled: "true"
      storageClass: nfs
      storage: 10Gi
