createCRD: false
git:
  ssh:
    secretName: flux-git-deploy
helm:
  versions: "v3"
chartsSyncInterval: "10m"
statusUpdateInterval: "10m"
prometheus:
  enabled: true
  serviceMonitor:
    create: false
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
