---

- name: "package-install: common packages"
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - gnupg-agent
    - gnupg2
    - haveged
    - hdparm
    # - htop # outdated v2, see below
    - jq
    - lvm2
    - nfs-common
    - psmisc
    - python3
    - python3-pip
    - python3-openssl
    - rsync
    - software-properties-common
    - unzip
    - vim
    install_recommends: false
    update_cache: true
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success

# Until focal has https://launchpad.net/ubuntu/+source/htop
- name: "package-install: htop latest"
  apt:
    deb: https://launchpad.net/ubuntu/+archive/primary/+files/htop_3.0.2-1_amd64.deb
  register: apt_install_htop
  retries: 5
  until: apt_install_htop is success
