---

- name: "package-install: common packages"
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - gnupg-agent
    - gnupg2
    - haveged
    - hdparm
    - htop
    - jq
    - nfs-common
    - psmisc
    - python3
    - python3-pip
    - python3-openssl
    - rsync
    - socat
    - software-properties-common
    - sudo
    - vim
    - zip
    install_recommends: false
    update_cache: true
    autoclean: true
    autoremove: true
  register: apt_install_common
  retries: 5
  until: apt_install_common is success

# - name: "package-install: kubectl"
#   become: true
#   get_url:
#     url: "https://storage.googleapis.com/kubernetes-release/release/v1.18.8/bin/linux/amd64/kubectl"
#     dest: "/usr/local/bin/kubectl"
#   when:
#   - "'master' in group_names"

# - name: "package-install: set kubectl permissions"
#   file:
#     path: "/usr/local/bin/kubectl"
#     mode: "0755"
#   when:
#   - "'master' in group_names"
