---
- hosts:
  - master
  - worker
  become: true
  vars_prompt:
    - name: "run_confirmation"
      prompt: "Are you sure you want to run this over the cluster? [Y/n]"
      default: "n"
      private: no
  any_errors_fatal: yes
  pre_tasks:
  - name: cluster | check confirmation
    fail: msg="Abort."
    when: run_confirmation != "Y"
  roles:
  - { role: xanmanning.k3s }
  - cluster
  # - cluster-kubeconfig
  # - cluster-cni
  # - cluster-meta
