---
- hosts: "{{ inventory_hostname }}"
  become: true
  gather_facts: true
  any_errors_fatal: yes
  
  tasks:
  - name: cluster-nuke | kill k3s
    command: /usr/local/bin/k3s-killall.sh

  - name: cluster-nuke | uninstall k3s
    command:
      cmd: /usr/local/bin/k3s-uninstall.sh
      removes: /usr/local/bin/k3s-uninstall.sh

  - name: cluster-nuke | uninstall k3s agent
    command:
      cmd: /usr/local/bin/k3s-agent-uninstall.sh
      removes: /usr/local/bin/k3s-agent-uninstall.sh

  - name: cluster-nuke | gather list of CNI files to delete
    find:
      paths: /etc/cni/net.d
      patterns: "*"
    register: files_to_delete

  - name: cluster-nuke | delete CNI files
    file:
      path: "{{ item.path }}"
      state: absent
    loop: "{{ files_to_delete.files }}"

  - name: cluster-nuke | reboot
    reboot:
      msg: "Nodes are being rebooted..."
    ignore_errors: true
