---
- hosts:
  - master
  - worker
  become: true
  gather_facts: true
  vars_prompt:
    - name: "restart_confirmation"
      prompt: "Restart nodes when complete? [Y/n]"
      default: "n"
      private: no
  roles:
  - operating-system
  tasks:
  - name: reboot
    reboot:
      msg: "Nodes are being rebooted..."
    ignore_errors: true
    when: restart_confirmation == "Y"