- hosts:
  - worker
  become: true
  gather_facts: true
  any_errors_fatal: yes
  
  - name: check longhorn is enabled
    fail:
      msg: "Abort."
    when:
    - longhorn.enabled is defined
    - not longhorn.enabled

  roles:
  - longhorn
