---
- hosts:
  - master
  - worker
  become: true
  gather_facts: true
  vars_prompt:
    - name: "run_confirmation"
      prompt: "Restart nodes when complete? [Y/n]"
      default: "n"
      private: no
  roles:
  - os
  tasks:
  - name: reboot
    reboot:
      msg: "Nodes are being rebooted..."
    ignore_errors: true
    when: run_confirmation == "Y"
