---
- hosts:
  - master
  - worker
  become: true
  gather_facts: true
  roles:
  - os
  tasks:
  - name: os-prepare | reboot
    ignore_errors: true
    reboot:
      msg: "Nodes are being rebooted..."
    tags:
    - always
