helmOperator:
  create: false
git:
  url: "git@github.com:carpenike/k3s-bootstrap"
  path: "cluster"
registry:
  rps: 1
  burst: 1
memcached:
prometheus:
  enabled: true
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
syncGarbageCollection:
  enabled: true
  dry: false
