#
# Below vars are for the xanmanning.k3s role
# ...see https://github.com/PyratLabs/ansible-role-k3s#group-variables
#

# Do not deploy the following
k3s_no_traefik: true
k3s_no_servicelb: true
k3s_no_metrics_server: true
k3s_no_flannel: true
k3s_no_local_storage: true
k3s_flannel_backend: "none"

# IP range for k3s nodes and services
k3s_cluster_cidr: "10.33.0.0/16"
k3s_service_cidr: "10.55.0.0/16"

# K3S version to install
k3s_release_version: "v1.24.7+k3s1"

# k3s_server install options
k3s_server:
  cluster-cidr: "10.33.0.0/16"
  service-cidr: "10.55.0.0/16"
# flannel-backend: "none"  # This needs to be in quotes
  data-dir: "/data/rancher/k3s" # Move the states and object storage to a second disk '/data'
  disable:
    - traefik
    - coredns
    - servicelb
  tls-san:
    - "{{ keepalived.vip }}"
    - "k3s-master-vip"
  debug: true
  disable-cloud-controller: true
  disable-network-policy: true
# disable-kube-proxy: true

k3s_install_hard_links: true

# k3s_default_local_storage_path: "/dev/shm/k8s"

# Use a specific control node address. IP or FQDN.
# ...k8s-master-vip is defined in /etc/hosts of all nodes if you are using keepalived
k3s_control_node_address: "{{ 'k3s-master-vip' if keepalived.enabled is defined and keepalived.enabled else groups['master'][0] }}"

# Elevate privileges while installing
k3s_become_for_all: true
k3s_become: true

# Disable kube-proxy
k3s_disable_kube_proxy: "{{ true if ((cilium_kube_router.enabled is defined and cilium_kube_router.enabled) or (calico.ebpf.enabled is defined and calico.ebpf.enabled)) else false }}"

# Disable k3s default cloud controller manager.
k3s_disable_cloud_controller: true

# Disable k3s default network policy controller.
# kube-router has it's own network-policy controller (or so it seems)
# https://github.com/rancher/k3s/issues/1308
k3s_disable_network_policy: "{{ true if cilium_kube_router.enabled is defined and cilium_kube_router.enabled else false }}"
# k3s_disable_network_policy: false

# Use experimental features (spooky!)
k3s_use_experimental: true

# Enable any feature-gates
k3s_kubelet_args:
- feature-gates: ExternalPolicyForExternalIP=true

# Enable debugging
k3s_debug: true

# Add additional hosname or IP as Subject Alternate Name in the TLS cert
k3s_tls_san:
- "{{ keepalived.vip }}"
- "k3s-master-vip"

# Use embedded etcd
k3s_etcd_datastore: true
