# Configure a pull thru cache using an existing registry
# ...requires a registry cache already set up
registry:
  cache:
    enabled: false
    address: "http://192.168.99.99:8082"
  custom:
    enabled: false
    address: "http://x.x.x.x:5000"
    username: "username"
    password: "password"
