# .github/workflows/ci.yml
name: CI
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 'Terraform Lint (Azure)'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.21
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: 'test/azure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Lint Ansible Playbooks
        # replace "master" with any valid ref
        uses: ansible/ansible-lint-action@master
        with:
          # [required]
          # Paths to ansible files (i.e., playbooks, tasks, handlers etc..)
          # or valid Ansible directories according to the Ansible role
          # directory structure.
          # If you want to lint multiple ansible files, use the following syntax
          # targets: |
          #   playbook_1.yml
          #   playbook_2.yml
          targets: |
            ansible/bootstrap.yml
          # [optional]
          # Arguments to be passed to the ansible-lint
  
          # Options:
          #   -q                    quieter, although not silent output
          #   -p                    parseable output in the format of pep8
          #   --parseable-severity  parseable output including severity of rule
          #   -r RULESDIR           specify one or more rules directories using one or
          #                         more -r arguments. Any -r flags override the default
          #                         rules in ansiblelint/rules, unless -R is also used.
          #   -R                    Use default rules in ansiblelint/rules in addition to
          #                         any extra
          #                         rules directories specified with -r. There is no need
          #                         to specify this if no -r flags are used
          #   -t TAGS               only check rules whose id/tags match these values
          #   -x SKIP_LIST          only check rules whose id/tags do not match these
          #                         values
          #   --nocolor             disable colored output
          #   --exclude=EXCLUDE_PATHS
          #                         path to directories or files to skip. This option is
          #                         repeatable.
          #   -c C                  Specify configuration file to use. Defaults to ".ansible-lint"
          args: ""