---

- name: Add Flux Repo
  command: "{{ item }}"
  with_items:
    - helm repo add fluxcd https://charts.fluxcd.io
  register: flux_repo_results
  environment:
    KUBECONFIG: "{{ REPO_ROOT }}/kubeconfig"
  changed_when: "'has been added to your repositories' in flux_repo_results.stdout"
  until: "'has been added to your repositories' in flux_repo_results.stdout"
  retries: 6
  delay: 10

- name: Deploy Helm Operator
  command: "{{ item }}"
  with_items:
    - "helm upgrade --install helm-operator --values {{ helm_operator_values }} --namespace flux fluxcd/helm-operator"
  register: helm_operator_results
  environment:
    KUBECONFIG: "{{ REPO_ROOT }}/kubeconfig"
  changed_when: "'has been upgraded' in helm_operator_results.stdout"
  until: "'has been upgraded' in helm_operator_results.stdout"
  retries: 10
  delay: 10
